name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install git-lfs
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git clone https://abhisheko97:$HF_TOKEN@huggingface.co/spaces/abhisheko97/Bill_Splitter_Splitwise space

          rsync -av --exclude '.git' --delete ./ space/

          cd space
          git add .
          git commit -m "Update from GitHub CI" || echo "No changes"
          git push